# Project Metadata
site_name: A guide to map modding in FiveM
site_description: A comprehensive guide to mapping and level design in FiveM
site_author: Adxtti
site_url: https://github.com/notneopallium/a-guide-to-map-modding-in-fivem

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - content.code.annotate
  palette:
    primary: teal
    accent: orange

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Introduction:
      - 1.1 What is Mapping?: intro/what-is-mapping.md
      - 1.2 Understanding GTA V file formats: intro/understanding-formats.md